---
  - name: install apache and upload some index.html
    hosts: aws
    become: yes

    vars:
      source_file: ./myweb/index.html
      destin_file: /var/www/html

    tasks:
    - name: check and print distribution version
      debug: var=ansible_os_family 

    - block: #------RED HAT-------

        - name: install apache
          yum: name=httpd state=latest

        - name: copy index.html to webserver
          copy: src={{source_file}} dest={{destin_file}} mode=0555
          notify: Restart Apache RedHat

        - name: enable Apache
          service: name=httpd state=started enabled=yes

      when: ansible_os_family == "RedHat"

    - block:  #------UBUNTU

        - name: install apache2
          apt: name=apache2 state=latest

        - name: copy index.html
          copy: src={{source_file}} dest={{destin_file}} mode=0555
          notify: Restart Apache Debian

        - name: enabled apache2
          service: name=apache2 state=started enabled=yes

      when: ansible_os_family == "Debian"

    handlers:
    - name: Restart Apache RedHat
      service: name=httpd state=restarted

    - name: Restart Apache Debian
      service: name=apache2 state=restarted
